name: ubuntu-vnc
services:
  server:
    image: czhujer/ubuntu-vnc
#    build:
#      dockerfile: Dockerfile
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - 6080:6080
#      - 5901:5901
